import = [ "~/.config/alacritty/dracula.toml" ]

[font]
normal = { family = "Hack Nerd Font" }
size = 12

[window]
opacity = 0.98

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"
